// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFse3wlH9z3bWfSlzZ7xFc7VHrfLzmlKA',
    appId: '1:253134655002:web:68eeab4e99337f63f68ba3',
    messagingSenderId: '253134655002',
    projectId: 'realestate-bf24d',
    authDomain: 'realestate-bf24d.firebaseapp.com',
    storageBucket: 'realestate-bf24d.appspot.com',
    measurementId: 'G-RKRVJN2P0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnEUM14aRbmiclzQvMekYTHsvm1aNzUc',
    appId: '1:253134655002:android:6845a47b372f8afff68ba3',
    messagingSenderId: '253134655002',
    projectId: 'realestate-bf24d',
    storageBucket: 'realestate-bf24d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJbWPEjrj6k7TccFFIhHXiHLSCRRQ_63Q',
    appId: '1:253134655002:ios:5e5c907814242fa6f68ba3',
    messagingSenderId: '253134655002',
    projectId: 'realestate-bf24d',
    storageBucket: 'realestate-bf24d.appspot.com',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJbWPEjrj6k7TccFFIhHXiHLSCRRQ_63Q',
    appId: '1:253134655002:ios:5e5c907814242fa6f68ba3',
    messagingSenderId: '253134655002',
    projectId: 'realestate-bf24d',
    storageBucket: 'realestate-bf24d.appspot.com',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFse3wlH9z3bWfSlzZ7xFc7VHrfLzmlKA',
    appId: '1:253134655002:web:7480a8cae548f15af68ba3',
    messagingSenderId: '253134655002',
    projectId: 'realestate-bf24d',
    authDomain: 'realestate-bf24d.firebaseapp.com',
    storageBucket: 'realestate-bf24d.appspot.com',
    measurementId: 'G-3VE1KQL0XZ',
  );
}
